apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-api
  namespace: case
  labels:
    app: participant-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participant-api
  template:
    metadata:
      labels:
        app: participant-api
    spec:
      containers:
      - name: participant-api
        image: sajeeth1009/participant-api-image:v0.12.1
        imagePullPolicy: Always
        env:
        - name: USE_DELETE_PARTICIPANT_DATA_ENDPOINT
          value: 'true'
        - name: GATEWAY_LISTEN_PORT
          value: "3231"
        - name: CORS_ALLOW_ORIGINS
          value: "https://case.com,http://case.com"
        - name: DEBUG_MODE
          value: "false"
        - name: ADDR_USER_MANAGEMENT_SERVICE
          value: user-management-service:5002
        - name: ADDR_STUDY_SERVICE
          value: study-service:5003
        - name: ADDR_MESSAGING_SERVICE
          value: messaging-service:5004
        - name: DISABLE_SIGNUP_WITH_EMAIL_ENDPOINT
          value: "false"
        - name: USE_RECAPTCHA
          value: "true"
        - name: RECAPTCHA_SECRET
          value: "false"
        ports:
        - containerPort: 3231
