apiVersion: v1
kind: ConfigMap
metadata:
  name: web-env-config
  namespace: case
data:
  env.local: |
    REACT_APP_API_BASE_URL=http://10.96.0.12:3231
    REACT_APP_DASHBOARD_IFRAME_URL=https://coneno.com
    REACT_APP_DEFAULT_INSTANCE=germany
    REACT_APP_CSP_CONNECT_URLS=http://10.96.0.11:3231 http://192.168.99.101:31000 ws://192.168.99.101:31000// https://www.google.com/recaptcha/ https://www.google.com/
    RECAPTCHA_PUBLIC_KEY=
    RECAPTCHA_SECRET_KEY=
    INLINE_RUNTIME_CHUNK=false  