apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: case-ingress-web
  namespace: italy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-site"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - tofudumplings.com
    secretName: site-tls-web
  rules:
    - host: tofudumplings.com
      http:
        paths:
          - backend:
              serviceName: web-client-service
              servicePort: 3100
            path: /
          - backend:
              serviceName: web-client-service
              servicePort: 3100
            path: /(home|faq|privacy|about|disclaimer|accessibility|contact|settings|link|survey)(.*)
