apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: case-ingress-web
  namespace: case
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-site"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - tofudumplings.com
    secretName: site-tls-web
  rules:
    - host: tofudumplings.com
      http:
        paths:
          - path: /
            backend:
              serviceName: web-client-service
              servicePort: 3100
          - path: /home
            backend:
              serviceName: web-client-service
              servicePort: 3100
          - path: /privacy(/|$)(.*)
            backend:
              serviceName: web-client-service
              servicePort: 3100
          - path: /faq(/|$)(.*)
            backend:
              serviceName: web-client-service
              servicePort: 3100
